on: [push, pull_request]

jobs:

  php-intl:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: sudo rm -f /etc/php/${{ matrix.php-version }}/cli/conf.d/*xdebug.ini
      - run: php${{ matrix.php-version }} -m ; php${{ matrix.php-version }} -v ; composer -V
      - run: composer install
      - run: php${{ matrix.php-version }} vendor/bin/phpunit --bootstrap tests/bootstrap.php tests
